site_name: Alogrithms
site_url: http://algorithms.sashaknop.com
repo_url: https://github.com/alexanderknop/algorithms
nav:
    - Home: index.md
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - tags
